import { ProcessWorkOrderResponse } from '../../../../domain/schemas/dto/response/process-work-order.response';
import {
  OrdenTrabajoDetalle,
  OrdenTrabajoTracking,
  OrdenTrabajoVistaCliente,
  WorkOrderListItem,
} from '../../../../domain/schemas/dto/response/work-orders.get.response';
import { ProcessWorkOrderSqlResponse } from '../../../interfaces/sql/process-work-order.sql.response';
import {
  OrdenTrabajoDetalleSqlResult,
  OrdenTrabajoTrackingSqlResult,
  OrdenTrabajoVistaClienteSqlResult,
  WorkOrderListItemSqlResult,
} from '../../../interfaces/sql/work-orders.sql.response';

export class ProcessWorkOrderAdapter {
  static fromProcessWorkOrderSqlResponseToProcessWorkOrderResponse(
    sqlResponse: ProcessWorkOrderSqlResponse,
  ): ProcessWorkOrderResponse {
    return {
      action: 'transition_work_order',
      recordId: sqlResponse.process_id.toString(),
      workOrderId: sqlResponse.work_order_id,
      orderCode: sqlResponse.order_code,
      cadastralKey: sqlResponse.cadastral_key,
      previousStatus: sqlResponse.previous_status,
      previousStatusName: sqlResponse.previous_status_name,
      newStatus: sqlResponse.new_status,
      newStatusName: sqlResponse.new_status_name,
      currentStatus: sqlResponse.current_status,
      createdByUserId: sqlResponse.processed_by_user_id,
      processedByUserId: sqlResponse.processed_by_user_id,
      comment: sqlResponse.comment,
      processedAt: sqlResponse.processed_at,
    };
  }

  static fromOrdenTrabajoDetalleSqlResultToOrdenTrabajoDetalle(
    sqlResult: OrdenTrabajoDetalleSqlResult,
  ): OrdenTrabajoDetalle {
    return {
      idOrdenTrabajo: sqlResult.id_orden_trabajo,
      codigoOrden: sqlResult.codigo_orden,
      numeroSecuencial: sqlResult.numero_secuencial,
      version: sqlResult.version,
      estado: sqlResult.estado,
      estadoLabel: sqlResult.estado_label,
      origen: sqlResult.origen,
      origenLabel: sqlResult.origen_label,
      idEntidadOrigen: sqlResult.id_entidad_origen,
      tipoTrabajo: sqlResult.tipo_trabajo,
      tipoTrabajoDescripcion: sqlResult.tipo_trabajo_descripcion,
      departamento: sqlResult.departamento,
      prioridad: sqlResult.prioridad,
      slaHoras: sqlResult.sla_horas,
      direccion: sqlResult.direccion,
      ubicacionDetalles: sqlResult.ubicacion_detalles,
      claveCatastral: sqlResult.clave_catastral,
      coordenadasPunto: sqlResult.coordenadas_punto,
      coordenadasTrazado: sqlResult.coordenadas_trazado,
      coordenadasArea: sqlResult.coordenadas_area,
      latitud: sqlResult.latitud,
      longitud: sqlResult.longitud,
      descripcion: sqlResult.descripcion,
      metadata: sqlResult.metadata,
      fechaCreacion: sqlResult.fecha_creacion,
      fechaAsignacion: sqlResult.fecha_asignacion,
      fechaInicioCampo: sqlResult.fecha_inicio_campo,
      fechaCompletada: sqlResult.fecha_completada,
      createdAt: sqlResult.created_at,
      updatedAt: sqlResult.updated_at,
      diasEnProceso: sqlResult.dias_en_proceso,
      horasTotalesProceso: sqlResult.horas_totales_proceso,
      horasHastaAsignacion: sqlResult.horas_hasta_asignacion,
      horasEjecucionCampo: sqlResult.horas_ejecucion_campo,
      escalaSupervisor: sqlResult.escala_supervisor,
      motivoEscalamiento: sqlResult.motivo_escalamiento,
      cumpleSla: sqlResult.cumple_sla,
      horasRestantesSla: sqlResult.horas_restantes_sla,
      tipoAsignacion: sqlResult.tipo_asignacion,
      inspectorUsername: sqlResult.inspector_username,
      inspectorNombre: sqlResult.inspector_nombre,
      idUsuarioAsignacion: sqlResult.id_usuario_asignacion,
      nombreAsignador: sqlResult.nombre_asignador,
      idUsuarioCompletacion: sqlResult.id_usuario_completacion,
      nombreCompletador: sqlResult.nombre_completador,
      idUsuarioCreador: sqlResult.id_usuario_creador,
      creadorUsername: sqlResult.creador_username,
      creadorNombre: sqlResult.creador_nombre,
      idCliente: sqlResult.id_cliente,
      personalAsignado: (sqlResult.personal_asignado ?? []).map((member) => ({
        idAsignacion: member.id_asignacion,
        idTrabajador: member.id_trabajador,
        nombreTrabajador: member.nombre_trabajador,
        rol: member.rol,
        esResponsable: member.es_responsable,
        fechaAsignacion: member.fecha_asignacion,
      })),
      materiales: (sqlResult.materiales ?? []).map((material) => ({
        idDetalle: material.id_detalle,
        idMaterial: material.id_material,
        codigoMaterial: material.codigo_material,
        nombreMaterial: material.nombre_material,
        descripcion: material.descripcion,
        cantidad: material.cantidad,
        costoUnitario: material.costo_unitario,
        subtotal: material.subtotal,
      })),
      adjuntos: (sqlResult.adjuntos ?? []).map((attachment) => ({
        idAdjunto: attachment.id_adjunto,
        nombreArchivo: attachment.nombre_archivo,
        url: attachment.url,
        tipoAdjunto: attachment.tipo_adjunto,
        mimeType: attachment.mime_type,
        fechaCarga: attachment.fecha_carga,
      })),
      observaciones: (sqlResult.observaciones ?? []).map((observation) => ({
        idObservacion: observation.id_observacion,
        texto: observation.texto,
        fecha: observation.fecha,
        autorId: observation.autor_id,
      })),
      costosAdicionales: (sqlResult.costos_adicionales ?? []).map((cost) => ({
        idCosto: cost.id_costo,
        concepto: cost.concepto,
        cantidad: cost.cantidad,
        costoUnitario: cost.costo_unitario,
        total: cost.total,
        codigo: cost.codigo,
        nombre: cost.nombre,
      })),
      costoTotalMateriales: sqlResult.costo_total_materiales,
      costoTotalAdicionales: sqlResult.costo_total_adicionales,
      costoTotalOrden: sqlResult.costo_total_orden,
      idInspeccion: sqlResult.id_inspeccion,
      checklistAprobado: sqlResult.checklist_aprobado,
      observacionesChecklist: sqlResult.observaciones_checklist,
      idControl: sqlResult.id_control,
      calidadAprobada: sqlResult.calidad_aprobada,
      comentariosCalidad: sqlResult.comentarios_calidad,
      idEncuesta: sqlResult.id_encuesta,
      calificacionSatisfaccion: sqlResult.calificacion_satisfaccion,
      comentariosSatisfaccion: sqlResult.comentarios_satisfaccion,
      idCorte: sqlResult.id_corte,
      tipoCorte: sqlResult.tipo_corte,
      sectorAfectado: sqlResult.sector_afectado,
      corteFechaInicio: sqlResult.corte_fecha_inicio,
      corteFechaFinEstimada: sqlResult.corte_fecha_fin_estimada,
      corteFechaRestablecido: sqlResult.corte_fecha_restablecido,
      corteNotificado: sqlResult.corte_notificado,
      idOrdenPadre: sqlResult.id_orden_padre,
      codigoOrdenPadre: sqlResult.codigo_orden_padre,
    };
  }

  static fromOrdenTrabajoTrackingSqlResultToOrdenTrabajoTracking(
    sqlResult: OrdenTrabajoTrackingSqlResult,
  ): OrdenTrabajoTracking {
    return {
      idOrdenTrabajo: sqlResult.id_orden_trabajo,
      codigoOrden: sqlResult.codigo_orden,
      numeroSecuencial: sqlResult.numero_secuencial,
      origen: sqlResult.origen,
      idEntidadOrigen: sqlResult.id_entidad_origen,
      tipoTrabajo: sqlResult.tipo_trabajo,
      departamento: sqlResult.departamento,
      prioridad: sqlResult.prioridad,
      slaHoras: sqlResult.sla_horas,
      direccion: sqlResult.direccion,
      claveCatastral: sqlResult.clave_catastral,
      fechaCreacionEs: sqlResult.fecha_creacion_es,
      estadoCodigo: sqlResult.estado_codigo,
      estadoActualLabel: sqlResult.estado_actual_label,
      escalaSupervisor: sqlResult.escala_supervisor,
      motivoEscalamiento: sqlResult.motivo_escalamiento,
      diasEnProceso: sqlResult.dias_en_proceso,
      horasTotalesProceso: sqlResult.horas_totales_proceso,
      horasHastaAsignacion: sqlResult.horas_restantes_sla,
      slaVencido: sqlResult.sla_vencido,
      fechaCreacion: sqlResult.fecha_creacion,
      fechaAsignacion: sqlResult.fecha_asignacion,
      fechaInicioCampo: sqlResult.fecha_inicio_campo,
      fechaCompletada: sqlResult.fecha_completada,
      createdAt: sqlResult.created_at,
      updatedAt: sqlResult.updated_at,
      ultimoMovimiento: sqlResult.ultimo_movimiento,
      ultimoComentario: sqlResult.ultimo_comentario,
      ultimoEstadoCodigo: sqlResult.ultimo_estado_codigo,
      adjuntosTotal: sqlResult.adjuntos_total,
      materialesTotal: sqlResult.materiales_total,
      costoTotalMateriales: sqlResult.costo_total_materiales,
      costoTotalAdicionales: sqlResult.costo_total_adicionales,
      observacionesTotal: sqlResult.observaciones_total,
      rechazosCalidad: sqlResult.rechazos_calidad,
      rechazosChecklist: sqlResult.rechazos_checklist,
      tipoAsignacion: sqlResult.tipo_asignacion,
      asignadoUsername: sqlResult.asignado_username,
      asignadoNombre: sqlResult.asignado_nombre,
      calificacionSatisfaccion: sqlResult.calificacion_satisfaccion,
      idCliente: sqlResult.id_cliente,
      historial: sqlResult.historial
        ? sqlResult.historial.map((item) => ({
            estado: item.estado,
            estadoLabel: item.estadoLabel,
            estadoAnterior: item.estadoAnterior,
            fecha: item.fecha,
            comentario: item.comentario,
            usuarioId: item.usuario_id,
          }))
        : null,
    };
  }

  static fromOrdenTrabajoVistaClienteSqlResultToOrdenTrabajoVistaCliente(
    sqlResult: OrdenTrabajoVistaClienteSqlResult,
  ): OrdenTrabajoVistaCliente {
    return {
      idOrdenTrabajo: sqlResult.id_orden_trabajo,
      tipoOrden: sqlResult.tipo_orden,
      codigoOrden: sqlResult.codigo_orden,
      numeroSecuencial: sqlResult.numero_secuencial,
      tipoTrabajo: sqlResult.tipo_trabajo,
      departamentoEjecutor: sqlResult.departamento_ejecutor,
      descripcion: sqlResult.descripcion,
      estadoCodigo: sqlResult.estado_codigo,
      estadoLabel: sqlResult.estado_label,
      estadoDescripcion: sqlResult.estado_descripcion,
      progresoPct: sqlResult.progreso_pct,
      prioridad: sqlResult.prioridad,
      slaHoras: sqlResult.sla_horas,
      cumpleSla: sqlResult.cumple_sla,
      fechaCreacion: sqlResult.fecha_creacion,
      fechaAsignacion: sqlResult.fecha_asignacion,
      fechaInicioCampo: sqlResult.fecha_inicio_campo,
      fechaCompletada: sqlResult.fecha_completada,
      diasEnProceso: sqlResult.dias_en_proceso,
      fechaCreacionEs: sqlResult.fecha_creacion_es,
      direccionTrabajo: sqlResult.direccion_trabajo,
      ubicacionDetalles: sqlResult.ubicacion_detalles,
      latitud: sqlResult.latitud,
      longitud: sqlResult.longitud,
      tipoAsignacion: sqlResult.tipo_asignacion,
      tecnicoUsername: sqlResult.tecnico_username,
      tecnicoNombre: sqlResult.tecnico_nombre,
      ultimaActualizacion: sqlResult.ultima_actualizacion,
      ultimoComentarioTecnico: sqlResult.ultimo_comentario_tecnico,
      totalFotosEvidencia: sqlResult.total_fotos_evidencia,
      fotosEvidencia: (sqlResult.fotos_evidencia ?? []).map((photo) => ({
        nombre: photo.nombre,
        url: photo.url,
        tipo: photo.tipo,
        fechaCarga: photo.fecha_carga,
      })),
      checklistAprobado: sqlResult.checklist_aprobado,
      trabajoAprobadoCalidad: sqlResult.trabajo_aprobado_calidad,
      comentariosCalidad: sqlResult.comentarios_calidad,
      calificacionSatisfaccion: sqlResult.calificacion_satisfaccion,
      comentariosEncuesta: sqlResult.comentarios_encuesta,
      encuestaCompletada: sqlResult.encuesta_completada,
      tipoCorte: sqlResult.tipo_corte,
      sectorAfectado: sqlResult.sector_afectado,
      corteInicio: sqlResult.corte_inicio,
      corteFinEstimado: sqlResult.corte_fin_estimado,
      fechaRestablecido: sqlResult.fecha_restablecido,
      corteNotificado: sqlResult.corte_notificado,
      idCliente: sqlResult.id_cliente,
      historialEstados: sqlResult.historial_estados
        ? sqlResult.historial_estados.map((item) => ({
            estado: item.estado,
            estadoLabel: item.estadoLabel,
            estadoAnterior: item.estadoAnterior,
            fecha: item.fecha,
            comentario: item.comentario,
            usuarioId: item.usuario_id,
          }))
        : null,
    };
  }

  static fromWorkOrderListItemSqlResultToWorkOrderListItem(
    sqlResult: WorkOrderListItemSqlResult,
  ): WorkOrderListItem {
    return {
      workOrderId: sqlResult.work_order_id,
      orderCode: sqlResult.order_code,
      origin: sqlResult.origin,
      workTypeId: sqlResult.work_type_id,
      workTypeName: sqlResult.work_type_name,
      priorityId: sqlResult.priority_id,
      clientId: sqlResult.client_id,
      clientName: sqlResult.client_name,
      personType: sqlResult.person_type,
      status: sqlResult.status,
      creationDate: sqlResult.creation_date,
      assignationDate: sqlResult.assignation_date,
      completionDate: sqlResult.completion_date,
      description: sqlResult.description,
      location: sqlResult.location,
      cadastralKey: sqlResult.cadastral_key,
      coordinates: sqlResult.coordinates,
      createdUserId: sqlResult.created_user_id,
      assignedUserId: sqlResult.assigned_user_id,
      completedUserId: sqlResult.completed_user_id,
      metadata: sqlResult.metadata ? JSON.parse(sqlResult.metadata) : null,
      isDeleted: sqlResult.is_deleted,
    };
  }
}
